### ISSUE TITLE
Em Portugol Prfv

### ISSUE THREAD

**Issue by RudisonF** [edwardlacerda/Portugol#1]
1) É  obrigatório  utilizar  um  único  FACA  ENQUANTO.  Desenvolva  um algoritmo que receba o valor de uma diária no hotel e a quantidade de dias de hospedagem.  Valide  as  informações,  ou  seja,  caso  o  usuário  insira  dados inválidos  não  permita  que  ele  saia  do  laço  de  repetição  até  informar  dados válidos.
As condições são:
    Nenhum dos valores pode ser negativo.
    A quantidade de dias não pode ser maior que 30.
Em caso de informação inválida escreva na tela “Valor inválido”. Ao final de tudo escreva “Fim do programa”

**Comment by edwardlacerda** [comment]
Desculpe pela demora, não tiha visto seu comentário.

você pode resolver dessa forma:

programa {

    funcao inicio() {
        real valor_diaria
        real quantidade_dias

        faca {
            escreva("Digite o valor da diária do hotel: ")
            leia(valor_diaria)
            escreva("Digite a quantidade de dias de hospedagem: ")
            leia(quantidade_dias)
            
            se (valor_diaria < 0 ou quantidade_dias < 0 ou quantidade_dias > 30) {
                escreva("Valor inválido\n")
            }
        } enquanto (valor_diaria < 0 ou quantidade_dias < 0 ou quantidade_dias > 30)

        escreva("Fim do programa\n")
    }
}
